### ISSUE TITLE
Implement login functionality

### ISSUE THREAD

**Issue by yosrada** [WebAhead-cs2/caps-look#45]
Implement the login actual functionality:

- [x] when user login to the app, A request shall be sent to the server. 

- [x] handle a UI state accordingly(loading button?).

- [x] show an error message to the user in case login failed

- [x] redirect the user to the home page in case login succeed

**Comment by Karyum** [comment]
@tawfiknasser @majdya this was already done no ?

**Comment by Karyum** [comment]
Oh my bad, I guess this is not creating the login page, this is connecting the login page to the API, if you could further add details on the tasks that would be _great.._

**Comment by yosrada** [comment]
I didn’t write this task , I choosed it, But it’s not a problem i will add
an explanation🫡

**Comment by Karyum** [comment]
# 🫡

**Comment by tawfiknasser** [comment]
Implement the login actual functionality:
- when user login to the app, A request shall be sent to the server. handle a UI state accordingly(loading button?).
- show an error message to the user in case login failed
- redirect the user to the home page in case login succeed
